package com.mailist.marketing.analytics.interfaces.dto;

import com.mailist.marketing.analytics.domain.valueobject.ReportFormat;
import com.mailist.marketing.analytics.domain.valueobject.ReportType;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Value;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class ReportDto {
    
    @Value
    @Builder
    @Schema(description = "Report response")
    public static class Response {
        @Schema(description = "Report ID", example = "1")
        Long id;
        
        @Schema(description = "Report name", example = "Campaign Analytics Report")
        String name;
        
        @Schema(description = "Report description", example = "Analytics for Q4 2024 email campaigns")
        String description;
        
        @Schema(description = "Report type", example = "CAMPAIGN")
        ReportType reportType;
        
        @Schema(description = "Report format", example = "PDF")
        ReportFormat reportFormat;
        
        @Schema(description = "Associated entity ID", example = "123")
        Long entityId;
        
        @Schema(description = "Report data")
        ReportDataDto data;
        
        @Schema(description = "Generation timestamp")
        LocalDateTime generatedAt;
        
        @Schema(description = "Generated by user", example = "admin@example.com")
        String generatedBy;
        
        @Schema(description = "File path for downloaded reports")
        String filePath;
        
        @Schema(description = "File size in bytes", example = "51200")
        Long fileSize;
        
        @Schema(description = "Report expiration timestamp")
        LocalDateTime expiresAt;
        
        @Schema(description = "Whether report has expired", example = "false")
        Boolean isExpired;
        
        @Schema(description = "Whether report has associated file", example = "true")
        Boolean hasFile;
    }
    
    @Value
    @Builder
    @Schema(description = "Generate report request")
    public static class GenerateRequest {
        @NotBlank(message = "Name is required")
        @Schema(description = "Report name", example = "Campaign Analytics Report", required = true)
        String name;
        
        @Schema(description = "Report description", example = "Analytics for Q4 2024 email campaigns")
        String description;
        
        @NotNull(message = "Report type is required")
        @Schema(description = "Report type", example = "CAMPAIGN", required = true)
        ReportType reportType;
        
        @NotNull(message = "Report format is required")
        @Schema(description = "Report format", example = "PDF", required = true)
        ReportFormat reportFormat;
        
        @Schema(description = "Associated entity ID", example = "123")
        Long entityId;
        
        @Schema(description = "Period start date", example = "2024-01-01T00:00:00")
        LocalDateTime startDate;
        
        @Schema(description = "Period end date", example = "2024-12-31T23:59:59")
        LocalDateTime endDate;
        
        @Schema(description = "Custom filters in JSON format", example = "{\"status\": \"sent\"}")
        String customFilters;
    }
    
    @Value
    @Builder
    @Schema(description = "Export report request")
    public static class ExportRequest {
        @NotNull(message = "Export format is required")
        @Schema(description = "Export format", example = "CSV", required = true)
        ReportFormat exportFormat;
    }
    
    @Value
    @Builder
    @Schema(description = "Report data")
    public static class ReportDataDto {
        @Schema(description = "Total emails sent", example = "1000")
        Long totalSent;
        
        @Schema(description = "Total emails delivered", example = "950")
        Long totalDelivered;
        
        @Schema(description = "Total emails opened", example = "380")
        Long totalOpened;
        
        @Schema(description = "Total emails clicked", example = "76")
        Long totalClicked;
        
        @Schema(description = "Total emails bounced", example = "50")
        Long totalBounced;
        
        @Schema(description = "Total unsubscriptions", example = "5")
        Long totalUnsubscribed;
        
        @Schema(description = "Total contacts", example = "5000")
        Long totalContacts;
        
        @Schema(description = "Active campaigns", example = "25")
        Long activeCampaigns;
        
        @Schema(description = "Active automations", example = "12")
        Long activeAutomations;
        
        @Schema(description = "Delivery rate percentage", example = "95.0")
        BigDecimal deliveryRate;
        
        @Schema(description = "Open rate percentage", example = "40.0")
        BigDecimal openRate;
        
        @Schema(description = "Click rate percentage", example = "20.0")
        BigDecimal clickRate;
        
        @Schema(description = "Bounce rate percentage", example = "5.0")
        BigDecimal bounceRate;
        
        @Schema(description = "Unsubscribe rate percentage", example = "0.5")
        BigDecimal unsubscribeRate;
        
        @Schema(description = "Report period start")
        LocalDateTime periodStart;
        
        @Schema(description = "Report period end")
        LocalDateTime periodEnd;
        
        @Schema(description = "Additional data in JSON format")
        String additionalData;
    }
}