package com.mailist.mailist.analytics.infrastructure.exporter;

import com.mailist.mailist.analytics.application.port.out.ReportExporter;
import com.mailist.mailist.analytics.domain.aggregate.Report;
import com.mailist.mailist.analytics.domain.valueobject.ReportFormat;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;

@Component
@Slf4j
public class DefaultReportExporter implements ReportExporter {
    
    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    
    @Override
    public ByteArrayOutputStream exportReport(Report report, ReportFormat format) {
        log.info("Exporting report ID: {} in format: {}", report.getId(), format);
        
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        
        try {
            switch (format) {
                case JSON -> exportAsJson(report, outputStream);
                case CSV -> exportAsCsv(report, outputStream);
                case PDF -> exportAsPdf(report, outputStream);
                case EXCEL -> exportAsExcel(report, outputStream);
                default -> throw new IllegalArgumentException("Unsupported format: " + format);
            }
        } catch (IOException e) {
            log.error("Error exporting report ID: {} in format: {}", report.getId(), format, e);
            throw new RuntimeException("Failed to export report", e);
        }
        
        return outputStream;
    }
    
    @Override
    public boolean supportsFormat(ReportFormat format) {
        return format == ReportFormat.JSON || format == ReportFormat.CSV || 
               format == ReportFormat.PDF || format == ReportFormat.EXCEL;
    }
    
    @Override
    public String getContentType(ReportFormat format) {
        return format.getMimeType();
    }
    
    @Override
    public long estimateFileSize(Report report, ReportFormat format) {
        // Basic estimation
        return switch (format) {
            case JSON -> 5000L;
            case CSV -> 2000L;
            case PDF -> 50000L;
            case EXCEL -> 25000L;
        };
    }
    
    private void exportAsJson(Report report, ByteArrayOutputStream outputStream) throws IOException {
        StringBuilder json = new StringBuilder();
        json.append("{\n");
        json.append(String.format("  \"id\": %d,\n", report.getId()));
        json.append(String.format("  \"name\": \"%s\",\n", escapeJson(report.getName())));
        json.append(String.format("  \"description\": \"%s\",\n", escapeJson(report.getDescription())));
        json.append(String.format("  \"reportType\": \"%s\",\n", report.getReportType()));
        json.append(String.format("  \"reportFormat\": \"%s\",\n", report.getReportFormat()));
        json.append(String.format("  \"entityId\": %s,\n", report.getEntityId()));
        json.append(String.format("  \"generatedAt\": \"%s\",\n", report.getGeneratedAt().format(DATE_TIME_FORMATTER)));
        json.append(String.format("  \"generatedBy\": \"%s\",\n", escapeJson(report.getGeneratedBy())));
        
        if (report.getReportData() != null) {
            json.append("  \"data\": {\n");
            json.append(String.format("    \"totalSent\": %s,\n", report.getReportData().getTotalSent()));
            json.append(String.format("    \"totalDelivered\": %s,\n", report.getReportData().getTotalDelivered()));
            json.append(String.format("    \"totalOpened\": %s,\n", report.getReportData().getTotalOpened()));
            json.append(String.format("    \"totalClicked\": %s,\n", report.getReportData().getTotalClicked()));
            json.append(String.format("    \"deliveryRate\": %s,\n", report.getReportData().getDeliveryRate()));
            json.append(String.format("    \"openRate\": %s,\n", report.getReportData().getOpenRate()));
            json.append(String.format("    \"clickRate\": %s\n", report.getReportData().getClickRate()));
            json.append("  }\n");
        }
        
        json.append("}");
        outputStream.write(json.toString().getBytes(StandardCharsets.UTF_8));
    }
    
    private void exportAsCsv(Report report, ByteArrayOutputStream outputStream) throws IOException {
        StringBuilder csv = new StringBuilder();
        csv.append("Metric,Value\n");
        csv.append(String.format("Report ID,%d\n", report.getId()));
        csv.append(String.format("Report Name,\"%s\"\n", escapeCsv(report.getName())));
        csv.append(String.format("Report Type,%s\n", report.getReportType()));
        csv.append(String.format("Generated At,%s\n", report.getGeneratedAt().format(DATE_TIME_FORMATTER)));
        csv.append(String.format("Generated By,\"%s\"\n", escapeCsv(report.getGeneratedBy())));
        
        if (report.getReportData() != null) {
            csv.append(String.format("Total Sent,%s\n", report.getReportData().getTotalSent()));
            csv.append(String.format("Total Delivered,%s\n", report.getReportData().getTotalDelivered()));
            csv.append(String.format("Total Opened,%s\n", report.getReportData().getTotalOpened()));
            csv.append(String.format("Total Clicked,%s\n", report.getReportData().getTotalClicked()));
            csv.append(String.format("Delivery Rate,%s%%\n", report.getReportData().getDeliveryRate()));
            csv.append(String.format("Open Rate,%s%%\n", report.getReportData().getOpenRate()));
            csv.append(String.format("Click Rate,%s%%\n", report.getReportData().getClickRate()));
        }
        
        outputStream.write(csv.toString().getBytes(StandardCharsets.UTF_8));
    }
    
    private void exportAsPdf(Report report, ByteArrayOutputStream outputStream) throws IOException {
        // Simplified PDF export - in real implementation, use a PDF library like iText
        String pdfContent = String.format(
                "PDF Report\n\nReport: %s\nType: %s\nGenerated: %s\nGenerated By: %s\n\nData: %s",
                report.getName(),
                report.getReportType(),
                report.getGeneratedAt().format(DATE_TIME_FORMATTER),
                report.getGeneratedBy(),
                report.getReportData() != null ? report.getReportData().toString() : "No data"
        );
        outputStream.write(pdfContent.getBytes(StandardCharsets.UTF_8));
    }
    
    private void exportAsExcel(Report report, ByteArrayOutputStream outputStream) throws IOException {
        // Simplified Excel export - in real implementation, use Apache POI
        String excelContent = String.format(
                "Excel Report\n\nReport: %s\nType: %s\nGenerated: %s\nGenerated By: %s\n\nData: %s",
                report.getName(),
                report.getReportType(),
                report.getGeneratedAt().format(DATE_TIME_FORMATTER),
                report.getGeneratedBy(),
                report.getReportData() != null ? report.getReportData().toString() : "No data"
        );
        outputStream.write(excelContent.getBytes(StandardCharsets.UTF_8));
    }
    
    private String escapeJson(String value) {
        if (value == null) return "";
        return value.replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r");
    }
    
    private String escapeCsv(String value) {
        if (value == null) return "";
        return value.replace("\"", "\"\"");
    }
}